[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false


[dependencies]
critical-section.workspace = true
defmt.workspace = true
embassy-executor.workspace = true
embassy-futures.workspace = true
embassy-sync.workspace = true
embassy-time.workspace = true
embedded-io-async.workspace = true
esp-hal.workspace = true
esp-println.workspace = true
serde = { version = "1.0.228", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.149", default-features = false, features = ["alloc"] }
trouble-host.workspace = true
