[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false


[dependencies]
critical-section.workspace = true
defmt.workspace = true
embassy-executor.workspace = true
embassy-futures.workspace = true
embassy-sync.workspace = true
embassy-time.workspace = true
embedded-io-async.workspace = true
esp-hal.workspace = true
esp-println.workspace = true
trouble-host.workspace = true
wincode = { version = "0.5.3", default-features = false, features = ["derive"] }
